import React from 'react'
import Head from 'next/head'
import PropTypes from 'prop-types'

export const AppHead = (props) => {
    const { title } = props
    return (
        <Head>
            <title>DC Corp Learning | {title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}
AppHead.propTypes = {
    title: PropTypes.string,
}
AppHead.defaultProps = {
    title: 'Home',
}
